# Nombre de la Acci칩n
name: Deploy to Firebase Hosting

# 1. EL TRIGGER (Disparador)
on:
  push:
    branches:
      - webdeploys

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Revisa tu c칩digo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configura Node.js (Vite necesita esto)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      # 3. Instala todas las dependencias
      - name: Install dependencies
        run: npm install

      # 4. LA MAGIA (Crea el .env)
      - name: Create .env file
        run: |
          echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}" >> .env
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "VITE_FIREBASE_DATABASE_URL=${{ secrets.VITE_FIREBASE_DATABASE_URL }}" >> .env
          echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}" >> .env
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}" >> .env
          echo "VITE_CLOUDINARY_CLOUD_NAME=${{ secrets.VITE_CLOUDINARY_CLOUD_NAME }}" >> .env
          echo "VITE_CLOUDINARY_UPLOAD_PRESET=${{ secrets.VITE_CLOUDINARY_UPLOAD_PRESET }}" >> .env
          echo "VITE_CLOUDINARY_PORTFOLIO_PRESET=${{ secrets.VITE_CLOUDINARY_PORTFOLIO_PRESET }}" >> .env
          echo "VITE_CLOUDINARY_CONTACT_PRESET=${{ secrets.VITE_CLOUDINARY_CONTACT_PRESET }}" >> .env
          echo "VITE_CLOUDINARY_BLOG_PRESET=${{ secrets.VITE_CLOUDINARY_BLOG_PRESET }}" >> .env

      # 5. Construye el proyecto
      # 'npm run build' leer치 el .env temporal y crear치 la carpeta 'dist'
      - name: Build project
        run: npm run build

      # 6. Despliega en Firebase
      # Sube la carpeta 'dist' a Firebase Hosting
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          channelId: live
          projectId: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # El token de login